#ifndef ENV_CLEANUP_STRUCTURE_HPP
#define ENV_CLEANUP_STRUCTURE_HPP

FWA_NAMESPACE_CORE_BEGIN
FWA_NAMESPACE_TEST_BEGIN

[[maybe_unused]] inline constexpr static auto unused_include_workaround{true};

FWA_NAMESPACE_TEST_END
FWA_NAMESPACE_CORE_END

// features

// std requirements

#undef STD_REQUIRE
#undef STD_REQUIRE_FALSE

// test macros

#undef REQUIRE_EQT
#undef REQUIRE_NET
#undef REQUIRES
#undef REQUIRES_FALSE

#undef ENV_TEST_SUITE_BEGIN
#undef ENV_TEST_SUITE_END
#undef ENV_TEST_CASE
#undef ENV_TEST_CASE_CLASS
#undef ENV_TEST_CASE_TMP

#undef FWA_GRAPH_TEST_SUITE_BEGIN
#undef FWA_GRAPH_TEST_SUITE_END
#undef FWA_GRAPH_TEST_CASE
#undef FWA_GRAPH_TEST_CASE_CLASS
#undef FWA_GRAPH_TEST_CASE_TMP

#undef FWA_EXEC_TEST_SUITE_BEGIN
#undef FWA_EXEC_TEST_SUITE_END
#undef FWA_EXEC_TEST_CASE
#undef FWA_EXEC_TEST_CASE_CLASS
#undef FWA_EXEC_TEST_CASE_TMP

// namespaces

// core -> std

#undef FWA_STD
#undef FWA_NAMESPACE_STD_END
#undef FWA_NAMESPACE_STD_BEGIN

// core -> global

#undef FWA_GLOBAL
#undef FWA_NAMESPACE_GLOBAL_END
#undef FWA_NAMESPACE_GLOBAL_BEGIN

// doctest

#undef FWA_DOCT

// fwa namespaces

#undef FWA_CORE
#undef FWA_NAMESPACE_CORE_END
#undef FWA_NAMESPACE_CORE_BEGIN

#undef FWA_GRAPH
#undef FWA_NAMESPACE_GRAPH_END
#undef FWA_NAMESPACE_GRAPH_BEGIN

#undef FWA_EXEC
#undef FWA_NAMESPACE_EXEC_END
#undef FWA_NAMESPACE_EXEC_BEGIN

// detail, test, format...

#undef FWA_NAMESPACE_DETAIL_END
#undef FWA_NAMESPACE_DETAIL_BEGIN

#undef FWA_NAMESPACE_TEST_END
#undef FWA_NAMESPACE_TEST_BEGIN

#undef FWA_NAMESPACE_BEGIN
#undef FWA_NAMESPACE_END

#undef FWA_FORMAT_NAMESPACE

#endif // ENV_CLEANUP_STRUCTURE_HPP
