function(env_prefix _name _prefix _out)
    if(_name)
        set(${_out} "${_prefix}_${_name}" PARENT_SCOPE)
    else()
        set(${_out} "${_prefix}" PARENT_SCOPE)
    endif()
endfunction()

function(env_suffix _name _suffix _out)
    if(_name)
        set(${_out} "${_name}_${_suffix}" PARENT_SCOPE)
    else()
        set(${_out} "${_suffix}" PARENT_SCOPE)
    endif()
endfunction()

function(env_inter _name _prefix _suffix _out)
    if(_name)
        set(${_out} "${_prefix}_${_name}_${_suffix}" PARENT_SCOPE)
    else()
        set(${_out} "${_prefix}_${_suffix}" PARENT_SCOPE)
    endif()
endfunction()
