function(env_prefix _name _prefix _out)
    string(REGEX MATCH "^${_prefix}" _match ${_name})
    if(_name AND NOT _match)
        set(${_out} "${_prefix}_${_name}" PARENT_SCOPE)
    elseif(_match)
        set(${_out} "${_name}" PARENT_SCOPE)
    else()
        set(${_out} "${_prefix}" PARENT_SCOPE)
    endif()
endfunction()

function(env_suffix _name _suffix _out)
    string(REGEX MATCH "${_suffix}\$" _match ${_name})
    if(_name AND NOT _match)
        set(${_out} "${_name}_${_suffix}" PARENT_SCOPE)
    elseif(_match)
        set(${_out} "${_name}" PARENT_SCOPE)
    else()
        set(${_out} "${_suffix}" PARENT_SCOPE)
    endif()
endfunction()
